### PR TITLE
fix: trigger warning toast when localstorage is full

### LINKED ISSUE #318: Trigger warning toast when the `localStorage` is full
```
localStorage.ts:19 Uncaught (in promise) QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'hollama-sessions' exceeded the quota.
    at Array.<anonymous> (localStorage.ts:19:17)
    at saveSession (sessions.ts:109:16)
    at handleSubmitNewMessage (+page.svelte:118:4)
    at Object.handleSubmit (+page.svelte:153:8)
    at HTMLButtonElement.submit (Prompt.svelte:258:64)
    at HTMLButtonElement.click (ButtonSubmit.svelte:7:40)
    at HTMLButtonElement.<anonymous> (Button.svelte:29:36)
```

### PR DESCRIPTION
**Pull request by mcendon**
Closes #318

* Added the warning toast with "Failed to save to localStorage" and error message when localStorage quota is full
* Playwright test added

### CODE REVIEW

**Review by fmaclen — CHANGES_REQUESTED** [review]
Thanks for submitting the PR, left you some minor notes.

**Review by fmaclen — CHANGES_REQUESTED** [review]
I think we are more or less there. Found a styling bug with the toast, it's rendered in a semi-transparent blue color:

Image

Probably because we are triggering it from a non-svelte file but I don't have time to really investigate.

So for now let's rely on a hack by adding `!important` to CSS classes to override inline styles:

```diff
// src/routes/+layout.svelte
<Toaster
	toastOptions={{
		unstyled: true,
		classes: {
			toast:
-				'shadow-xl px-4 py-3 flex items-center gap-x-3 max-w-full w-full rounded mx-auto text-xs mx-0',
+				'shadow-xl px-4 py-3 flex items-center gap-x-3 max-w-full w-full rounded mx-auto text-xs mx-0 !outline-none',
			loading: 'bg-shade-0',
			error: 'text-red-50 bg-red-700',
			success: 'text-emerald-50 bg-emerald-700',
-			warning: 'text-yellow-50 bg-yellow-700',
+			warning: 'text-yellow-50 !bg-yellow-700',
			info: 'bg-shade-1 text-neutral-500'
		}
	}}
	position="top-center"
/>
```

- Added `!outline-none` to remove blue border
- Added `!bg-yellow-700` to ensure yellow background

File: src/routes/+layout.svelte [hunk 1]
```diff
@@ -128,11 +128,11 @@
 		unstyled: true,
 		classes: {
 			toast:
-				'shadow-xl px-4 py-3 flex items-center gap-x-3 max-w-full w-full rounded mx-auto text-xs mx-0',
+				'shadow-xl px-4 py-3 flex items-center gap-x-3 max-w-full w-full rounded mx-auto text-xs mx-0 !outline-none',
 			loading: 'bg-shade-0',
 			error: 'text-red-50 bg-red-700',
 			success: 'text-emerald-50 bg-emerald-700',
-			warning: 'text-yellow-50 bg-yellow-700',
+			warning: 'text-yellow-50 bg-yellow-700 !bg-yellow-700',
```
Comment (fmaclen) [inline src/routes/+layout.svelte:135]: > I guess the problem is with the playwright test itself, because when running a local server and manually executes the test in the browser (I am using Chrome 138.0.7204.157 (Official Build) (64-bit) under Pop OS!) the toast styles are fine.

Oh, great catch! I think you are right, I just re-ran the test but took a screenshot instead of using the Trace Viewer and the colors are correct!

We can undo the hacks 👍

File: src/lib/localStorage.ts [hunk 2]
```diff
@@ -16,7 +17,24 @@ function createLocalStorageStore<T>(key: string, defaultValue: T) {
 
 	store.subscribe((value) => {
 		if (browser) {
-			localStorage.setItem(key, JSON.stringify(value));
+			try {
+				localStorage.setItem(key, JSON.stringify(value));
+			} catch (error) {
+				// Handle localStorage quota exceeded error
+				if (error instanceof DOMException && error.name === 'QuotaExceededError') {
+					toast.warning('Localstorage is full', {
```
Comment (fmaclen) [inline src/lib/localStorage.ts:25]:
```suggestion
					toast.warning('Local storage is full', {
```

File: tests/session-interaction.test.ts [hunk 3]
```diff
@@ -689,4 +689,45 @@ test.describe('Session interaction', () => {
...
+		await mockCompletionResponse(page, MOCK_SESSION_1_RESPONSE_1);
+		await promptTextarea.fill(
+			'Who would win in a fight between Sydney Sweeney and Olivia Rodrigo?'
+		);
+		await page.getByText('Run').click();
+
+		const toastLocator = page.locator('ol[data-sonner-toaster] li[data-type="warning"]');
+		await expect(toastLocator).toBeVisible();
+		await expect(toastLocator).toHaveCount(1);
+		await expect(toastLocator).toContainText('Localstorage is full');
```
Comment (fmaclen) [inline tests/session-interaction.test.ts:728]:
```suggestion
		await expect(toastLocator).toContainText('Local storage is full');
```

**Review by fmaclen — CHANGES_REQUESTED** [review]
Thanks for looking into the Playwright issue. Your earlier implementation appears to be working fine without the hacks.

Also left you 2 minor typo changes.

Other than that, we are good to go!

**Comment by mcendon** [comment]
Perfect Fernando, typo resolved and styling hack was reverted! Great, we are ready to go!

File: src/lib/localStorage.ts (hunk 2 above)
Comment (mcendon) [reply src/lib/localStorage.ts]: Done

**Comment by fmaclen** [comment]
Thanks for the contibution @mcendon!

**Comment by mcendon** [comment]
> Thanks for the contribution @mcendon!

You're welcome, Fernando. Count on me for other contributions—I'm short on time, but I'll help however I can! Cheers.
