### PR TITLE
fix: various minor bug fixes & styling updates

### LINKED ISSUE #210: Add styling for tables in markup responses
REF https://github.com/fmaclen/hollama/discussions/207

### PR DESCRIPTION
**Pull request by fmaclen**
Closes #210 

- Fixes styling for tables in markdown responses
- Fixes an issue where a prompt could be submitted without choosing a model first
- Fixes another issue where clearing a model and switching sessions made the **Run** button disabled
- Styling updates to model select field

### CODE REVIEW

File: src/lib/components/FieldSelect.svelte [hunk 1]
```diff
@@ -130,23 +130,25 @@
...
+										<div class="field-combobox-item-label">
+											<span class="field-combobox-item-label-option" title={option.label}>
+												{option.label}
+											</span>
+											{#if option.badge}
+												<Badge>{option.badge}</Badge>
+											{/if}
+										</div>
+									</Combobox.Item>
+								{/if}
```
Comment (fmaclen) [inline src/lib/components/FieldSelect.svelte:151]: Prevents rendering empty values

File: src/routes/sessions/[id]/+page.svelte [hunk 2]
```diff
@@ -106,6 +106,7 @@
 
 	function handleSubmit() {
 		if (!$editor.prompt) return;
+		if (!$session.model) return;
```
Comment (fmaclen) [inline src/routes/sessions/[id]/+page.svelte:109]: Prevents submitting prompt without a model
